### ISSUE TITLE
some dependencies missing?

### ISSUE THREAD

**Issue by leduke2000** [leojoubert/WikiSocio#1]
When installing the package I had a few errors, all related to the absence of some required packages, here is the list:
RcppProgress,NLP,slam
I think it is more devtools problem, which doesn't recursively install dependencies, I think.
That means that dependencies for dependencies may not be installed.

**Comment by leojoubert** [comment]
As shown here : http://stackoverflow.com/questions/38425529/does-install-github-recursively-install-dependencies this seems to be a devtools problem indeed. Have you tried to update devtools package first ?
